#! python


def build(ctx):

    for model in 'Japan', 'GBR':

        ctx(
            features='run_py_script',
            source='{}_SCM.py'.format(model),
            deps=[
                ctx.path_to(ctx, 'IN_DATA', 'Dataset_TermPaper.xlsx'),
            ],
            target=ctx.path_to(ctx, 'OUT_FIGURES', 'Synthetic_Control_Method_{}.png'.format(model))
        )

